name: Docker

on: [workflow_dispatch]

env:
  RUNNER_VERSION: 2.316.0

jobs:
  docker:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: scria1000-github-runner-win
          tags: latest
          registry: docker.io 
          dockerfile: dockerfile
          buildArgs: RUNNER_VERSION=${{ env.RUNNER_VERSION }}
          platform: windows/amd64
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          pushImage: false
