name: Publish Docker image

on: [workflow_dispatch]

env:
  RUNNER_VERSION: 2.316.0

jobs:
  docker:
    runs-on: windows-2019
    permissions:
      id-token: write
      packages: write
      attestations: write
      contents: read
    env:
      REGISTRY: index.docker.io
      IMAGE_NAME: scria1000/github-runner-windows
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest
          registry: docker.io 
          dockerfile: dockerfile
          buildArgs: RUNNER_VERSION=${{ env.RUNNER_VERSION }}
          platform: windows/amd64
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          pushImage: true

      - name: Get digest of image built in previous step
        id: get-digest
        if: success()
        shell: bash
        run: |
          digest=$(docker inspect --format '{{ index .RepoDigests 0 }}' ${{ env.IMAGE_NAME }} | cut -d "@" -f 2)
          echo "digest=$digest" >> $GITHUB_OUTPUT

      - name: Attest image
        uses: github-early-access/generate-build-provenance@main
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: '${{ steps.get-digest.outputs.digest }}'
          push-to-registry: true
